### ISSUE TITLE
Publish latest doc

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#186]
@pvlugter, I assume from the readme that the way to get the latest doc into prod is to build them using make and push those changes to the docs/current branch? Since I can't get make to work on my windows machine, should I create a request like this each time I'd like the docs updated? or is there a better way?

**Comment by pvlugter** [comment]
Docs are published automatically on releases. In general, we want to publish the docs with a release, so that the documentation for a feature is not published before it's actually available. We can deploy manually (with `make deploy`) for hot fixes to the docs, but I think enhancements and tweaks can just wait until the next release to be included. Is there an important fix that needs including now?

**Comment by rstento** [comment]
@pvlugter, is there any doc in main for features that haven't been released yet? If so, I"m fine waiting. But if there isn't, I think we've done some improvements that would be good to get out in the wild. @retgits, what do you think?

**Comment by ennru** [comment]
The most accurate view of unreleased things is the [release draft](https://github.com/lightbend/akkaserverless-java-sdk/releases) which lists merged PRs.

**Comment by pvlugter** [comment]
Hmm, something off with release drafter? The list has previously released PRs as well.

Manually deployed the doc changes. Will be available in the next build of the main docs.
