### ISSUE TITLE
Compilation problems with Actions without java_outer_classname

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#239]
Action codegen generates invalid code if there isn't a `java_outer_classname` option. That's not the case of the other components. 

See https://github.com/lightbend/akkaserverless-java-sdk/pull/237/files#diff-e2cacc5b119d9b80e7513c32929fe8e3603b078893d30718ea82c7024482db8dR19

**Comment by pvlugter** [comment]
It needs to take into account how classes will be generated, with the `java_multiple_files` option, the `java_outer_classname` option, what the proto file name is (which is converted to camel case), and if there's a message or service with the same name (in which case `OuterClass` will be appended). 

https://developers.google.com/protocol-buffers/docs/reference/java-generated#invocation

There's some handling for it, but probably doesn't cover all the combinations. And there may still be issues with the codegen for the other components as well.

**Comment by patriknw** [comment]
Could we be opinionated and say that `java_outer_classname` is mandatory? Codegen will fail fast if it's not defined.

I'm not quite sure how it works but naming is rather arbitary when `java_outer_classname` isn't defined, such as basing the name on the proto file name. I have only seen trouble without `java_outer_classname`.

It's anyway good to qualify the api and domain messages since they are often used in the same class (converting from one to the other), and Java doesn't have import renaming. E.g. `ShoppingCartDomain.LineItem` vs `ShoppingCartApi.LineItem`.

**Comment by pvlugter** [comment]
> Could we be opinionated and say that `java_outer_classname` is mandatory? Codegen will fail fast if it's not defined.

That could be easiest to do for now. As well as requiring `java_multiple_files` to not be set.

> I'm not quite sure how it works but naming is rather arbitary when `java_outer_classname` isn't defined, such as basing the name on the proto file name. I have only seen trouble without `java_outer_classname`.

If `java_multiple_files` is set then messages will be in separate classes, otherwise they'll be in the outer wrapper class. The name for that class will be from `java_outer_classname` if set, or a camel case version of the proto file name. If the default file-based name is the same as a service or message then it has `OuterClass` added. 

Currently there are some parts of this. The file name is converted:

https://github.com/lightbend/akkaserverless-java-sdk/blob/4073aacc54b3d6f6043f495d5a7b896a0d3c85d6/codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala#L95-L105

And checks for which options are enabled:

https://github.com/lightbend/akkaserverless-java-sdk/blob/4073aacc54b3d6f6043f495d5a7b896a0d3c85d6/codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala#L29-L38

So could only be a little more work to support this properly.
 
> It's anyway good to qualify the api and domain messages since they are often used in the same class (converting from one to the other), and Java doesn't have import renaming. E.g. `ShoppingCartDomain.LineItem` vs `ShoppingCartApi.LineItem`.

If the proto files are `shopping_cart_domain.proto` and `shopping_cart_api.proto` then they'll have the same outer class name without the `java_outer_classname` option.

For actions, there's likely to be a name clash with the service name (say `echo_action.proto` with `EchoAction` service) and then it becomes `EchoActionOuterClass`, which is not handled.
