### ISSUE TITLE
Stateful action context and async handlers

### ISSUE THREAD

**Issue by johanandren** [lightbend/akkaserverless-java-sdk#268]
The ActionContext is now a state on the Action that is set/reset around the call, but the call may do async things and expect to access it in a future/CS callback leading to something much like the good old close over context problem in actors. We should avoid giving users that grief if we can.

_Originally posted by @octonato in https://github.com/lightbend/akkaserverless-java-sdk/pull/258#discussion_r700514689_

**Comment by patriknw** [comment]
isn't that the reason for the `ActivatableContext`?

**Comment by johanandren** [comment]
This is different in that it actually is ok to use the same `ActionContext` instance in callbacks (and you may need that, at least the TCK does), but you can't call `actionContext()` since that has potentially been cleared, so you must make sure to capture it. (The reference to actor context was wrong, I was thinking about `sender()`).

**Comment by patriknw** [comment]
I see what you mean.

Do we create a new Action instance for each request (command)? Otherwise we would have a concurrency bug since the `actionContext` is an instance variable and there can be many Action calls executing at the same time.

Could we make use of that? Not clear the actionContext instance when the call returns. Then it is valid also in callbacks.

**Comment by johanandren** [comment]
I looked into this and we create a new instance of the action class for each incoming command, so while it isn't safe now (potentially accessing a mutable field from other threads) it would be safe to make the `ActionContext` a final field that we do not clear out after the command.
