### ISSUE TITLE
Remove nested directory in quickstart download zip files

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#380]
Because the target directory is defined via `akkasls` and it should unzip the content to that directory instead of an additional directory level.

**Comment by pvlugter** [comment]
Are these ever going to be downloaded and unzipped directly by users? Having a zip file unzip its contents into the current directory without realising it is always a pain. If it's only going to be possible via `akkasls` then makes sense, otherwise could be better to leave the unzipped directory and have the `akkasls` unzip and then move the directory to the target?

**Comment by retgits** [comment]
> Are these ever going to be downloaded and unzipped directly by users?

No, in our docs we specifically use the `akkasls quickstarts` command to download these zip files.

**Comment by pvlugter** [comment]
Ok, I'll update the zip to not include the base directory

**Comment by pvlugter** [comment]
Updated in #412. Should be applied to https://github.com/lightbend/akkaserverless-javascript-sdk/pull/184 as well.
