### ISSUE TITLE
Remove ReplicatedMap from API

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#48]
Use the more specialized map implementations that are built on top of ReplicatedMap
* ReplicatedCounterMap
* ReplicatedRegisterMap

We should probably add ReplicatedMultiMap to cover ReplicatedMap of ReplicatedSet values.

**Comment by pvlugter** [comment]
So this has ended up with these specialised replicated maps (counter map and register map) being added end-to-end — added to the protocol and using the specialised maps in Akka — so that the proxy sends messages specific to these CRDTs and SDKs can create these directly when an entity is initialised, either initially or after passivation. Otherwise the user needs to wrap an automatically initialised generic map with the specialised map (and for the JS SDK, the replicated entity state can't be set to the specialised map once initialised).

The generic replicated map could be removed now, but it could be useful to keep it as the only way to combine CRDTs currently, while recommending the specialised maps for most use cases.

**Comment by pvlugter** [comment]
Changes merged. I think we can close this now, with ReplicatedMap still available but prefer the specialised maps.
