### ISSUE TITLE
AkkaServerlessFactory might end up in empty package

### ISSUE THREAD

**Issue by jrudolph** [lightbend/akkaserverless-java-sdk#608]
The package name for the AkkaServerlessFactory is determined by the `longestCommonPrefix` which might be empty for a set of protos. In that case we should either fail or actually put it on the root level.

It would also be nice if the package could be customized (sbt configuration?).

**Comment by patriknw** [comment]
I assume this would be similar problem for Java

**Comment by johanandren** [comment]
Having heterogenous packages in proto descriptors will now break a project since the component generation incorrectly handles empty package. I think we could fix that, but there will be problems with the Components type in the default package for Java since the actual components, in other packages, refer to it and there is no way to import root package classes in Java as far as I know.

In addition to allow for specifying this, we should fail when the root package is empty with an explanation what to do about it.
