### ISSUE TITLE
ShoppingCartIntegrationTest is in the wrong package

### ISSUE THREAD

**Issue by max8github** [lightbend/akkaserverless-java-sdk#678]
From branch `main`, if you follow instructions from [here](https://developer.lightbend.com/docs/akka-serverless/quickstart/prebuilt-samples.html) for our [Shopping Cart example (using an Event Sourced Entity)](https://github.com/lightbend/akkaserverless-java-sdk/tree/main/samples/java-eventsourced-shopping-cart) and then `mvn compile` you see in `git status` that java classes get created in the wrong packages under `src`. There are two java classes in the `it` folder, both with the same name, `ShoppingCartIntegrationTest`:
```
./samples/java-eventsourced-shopping-cart/src/it/java/com/example/shoppingcart/ShoppingCartIntegrationTest.java
./samples/java-eventsourced-shopping-cart/src/it/java/com/example/shoppingcart/domain/ShoppingCartIntegrationTest.java
```
The first one is in the right package, but not in source control, the second is in source control, but with a package declaration that is wrong: `package com.example.shoppingcart.api;`

Steps to reproduce:
```
git clone git@github.com:lightbend/akkaserverless-java-sdk.git
cd akkaserverless-java-sdk/samples/java-eventsourced-shopping-cart
mvn compile
```

**Comment by raboof** [comment]
Thanks for the heads-up!

I suspect this is partly because `samples/java-eventsourced-shopping-cart/pom.xml` refers to version 0.8.0 of the SDK, but `main` has moved on since then (in particular #670).

You can use `./publishLocalM2.sh` in the root of the project to build the latest version of the SDK, and then `mvn -Dakkaserverless-sdk.version=$SDK_VERSION` to build with the latest SDK.

That said, indeed the location of `samples/java-eventsourced-shopping-cart/src/it/java/com/example/shoppingcart/ShoppingCartIntegrationTest.java` and its package declaration of `com.example.shoppingcart.api` don't match up, so that's definitely something to look into. Also, it seems curious that this wasn't caught by CI.

**Comment by johanandren** [comment]
For the record the package it is generated into was recently changed in main for https://github.com/lightbend/akkaserverless-java-sdk/issues/597

**Comment by johanandren** [comment]
Had to move it in #675 to make things compile, so will be fixed with that PR
