### ISSUE TITLE
Kafka quickstart

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#749]
From Leon: Building a quickstart for eventing, especially with our Kafka integration we're in a good place to let developers build awesome event-driven architectures. Let's help them a bit with an eventing quickstart

**Comment by beritou** [comment]
I have a suggestion for how this is implemented.

Rather than expanding Rather than expanding [cr-value-entity-java](https://developer.lightbend.com/docs/akka-serverless/java/quickstart/cr-value-entity-java.html) with more steps for Kafka, could this be created as a separate quickstart?

To be more specific, the end result would be another Java quickstart that we would add to the list:

![image](https://user-images.githubusercontent.com/6062111/153902632-ff05b019-f387-4eb8-8ddd-1427ab8c5a82.png)

The rationale for this is to keep our Quickstarts as small and focused as possible. This has a lot of benefits:
- more users attempt the quickstarts because they are shorter and less intimidating
- more users complete the quickstarts because they are fewer steps overall, fewer places to get stuck
- Lightbend can modify and maintain the quickstarts more easily because they are more modular
- Lightbend can get more detailed metrics on which Akka Serverless features our users are consuming quickstarts for

@patriknw @retgits

**Comment by franciscolopezsancho** [comment]
When expanding this example I thought that the next user that would attempt to use it would have more work to do and more understanding. Even though the user might have not been interested in any Pub/Sub at that moment.
To me what @beritou is suggesting makes a lot of sense.

**Comment by retgits** [comment]
> Rather than expanding Rather than expanding [cr-value-entity-java](https://developer.lightbend.com/docs/akka-serverless/java/quickstart/cr-value-entity-java.html) with more steps for Kafka, could this be created as a separate quickstart?

I agree, based on the original text of the story it should be a separate QuickStart https://github.com/lightbend/akkaserverless-docs/issues/811 for exactly the reasons you list :)

**Comment by patriknw** [comment]
@beritou That corresponds to what we have started, as far as I know. The directions I gave @franciscolopezsancho was to add a new quickstart and base it on the previous Customer Registry quickstart. That is what we have for Views and this would be similar for adding Kafka.

**Comment by franciscolopezsancho** [comment]
oh, then I got it wrong. My bad! 
I'm back to the righteous path.

**Comment by ennru** [comment]
It is available in DEV now... https://docs.akkaserverless.dev/java/quickstart/cr-value-entity-kafka-java.html
